baseURL = "https://xn--dtour-bsa.studio/"
defaultContentLanguage = "fr"
languageCode = "fr-FR"
title = "détour.studio"

theme = "detour"
sectionPagesMenu = "works"
buildFuture = true
rssLimit = 10

[params]
  description = "Studio de design et de développement de services numériques libres, conviviaux et qui ont du sens."

[params.works]
  order = [
    "développement web",
    "accompagnement",
    "édition numérique",
    "apprentissage",
    "contribution"
  ]

  [params.works."développement web"]
    icon = "👨‍💻"
    description = "Je construis pas à pas des logiciels pragmatiques, conviviaux et sobres, au service de vos enjeux, et de ceux d'un futur désirable sur Terre."
  [params.works."accompagnement"]
    icon = "🗺"
    description = "J'emmène et protège des équipes dans une direction où elles y trouvent du sens, du plaisir et de l'autonomie."
  [params.works."édition numérique"]
    icon = "📚"
    description = "Je crée des livres et documents à imprimer d'une nouvelle manière, avec un simple navigateur web."
  [params.works."apprentissage"]
    icon = "👥"
    description = "Je crée des formats doux et créatifs qui stimulent l'apprentissage et le partage de connaissances entre les personnes."
  [params.works."contribution"]
    icon = "👍"

[params.people]
  "Benjamin Grémillon" = "https://benjmng.eu"
  "Julie Blanc" = "https://julie-blanc.fr"
  "Julien Taquet" = "https://www.lesvoisinsdustudio.ch"
  "Paul Girard" = "https://medialab.sciencespo.fr/equipe/paul-girard/"
  "Samuel Huron" = "https://twitter.com/cybunk"

[outputFormats]
  [outputFormats.opml]
    basename = "collection"
    mediaType = "application/xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
