baseURL = "https://détour.studio/"
defaultContentLanguage = "fr"
languageCode = "fr-FR"
title = "détour.studio"

theme = "detour"

[params]
  description = "Studio de design et de développement de services numériques libres, conviviaux et qui ont du sens."


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
