baseURL = "https://détour.studio/"
defaultContentLanguage = "fr"
languageCode = "fr-FR"
title = "détour.studio"

theme = "detour"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
