name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: oncletom/rsync-deployments@patch-1
        with:
          SRC: public/
          DEST: /home/oncletom/www_detour_studio
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          USER_AND_HOST: oncletom@ssh-oncletom.alwaysdata.net
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
