name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: oncletom/rsync-deployments@patch-1
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules
          RSYNC_TARGET: oncletom@ssh-oncletom.alwaysdata.net:${HOME}/www_detour_studio
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOME: /home/oncletom
