name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: oncletom/rsync-deployments@patch-1
        with:
          RSYNC_BASEDIR: /public
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: oncletom@ssh-oncletom.alwaysdata.net:/home/oncletom/www_detour_studio
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOME: /home/oncletom
