name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: contention/rsync-deployments@v1.0.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOME: /home/oncletom
          1: -avzr --delete
          2: --exclude node_modules
          3: oncletom@ssh-oncletom.alwaysdata.net:${HOME}/www_detour_studio
